added README.md and data to InjectDataController
matviichuk92/Online-Shop pull request #12
Opened 2020-10-15 14:41 UTC by matviichuk92

2020-10-15 14:46 UTC, matviichuk92 commented
[Ось як це буде виглядати](https://github.com/matviichuk92/Online-Shop/blob/2fa75dcccb04951199bcebd5500eaa08c2fa05c4/README.md)

2020-10-15 16:08 UTC, AnaLanda commented on README.md
> +___________________________
```suggestion
An online project in the form of an internet shop prototype with a connection to a database (DB).
The shop presented in this project has the following functionality:
- registering users and saving hashed passwords in the DB;
- role-based access to pages for users and admins;
- users can: look through the products in the store and add them to their cart, edit the cart, 
place orders, and see all their previous orders;
- admins have access to all information about the users, their orders, and products in the store, which they can edit and delete.
___________________________
```

2020-10-15 16:09 UTC, AnaLanda commented on README.md
> +Project have N-tier architecture:
```suggestion
The project has an N-tier architecture: 
```

2020-10-15 16:09 UTC, AnaLanda commented on README.md
> +Also, four major entities: Product, User, ShoppingCart and Order.
```suggestion
The project also features four major entities: Product, User, ShoppingCart and Order.
```

2020-10-15 16:10 UTC, AnaLanda commented on README.md
> +Project correspond to SOLID, KISS and DRY principles. It's created with Java EE, MySQL, Maven, Apache Tomcat.
```suggestion
The project follows SOLID, KISS, and DRY principles. It was created with Java EE, MySQL, Maven, and Apache Tomcat.
```

2020-10-15 16:11 UTC, AnaLanda commented on README.md
> +- Fork project;
```suggestion
- Download the project to your machine;
```

2020-10-15 16:12 UTC, AnaLanda commented on README.md
> +- Register like regular user;
```suggestion
- Launch the project using the Tomcat Server;
- Register as a user on the website;
```

2020-10-15 16:13 UTC, AnaLanda commented on README.md
> +- Logout and log in like admin(login - boss, password - 123) and check admin functionality;
```suggestion
- Log in to the website, click on the button "Inject data" and check the user functionality;
- Logout and log in as an admin using login "boss" and password "123" and check the admin functionality;
```

2020-10-15 16:14 UTC, AnaLanda reviewed
Looks good! I added a couple language-related suggestions)

2020-10-16 07:18 UTC, matviichuk92 commented
> Looks good! I added a couple language-related suggestions)

 I owe you one!

2020-10-16 07:59 UTC, KseniiaMakarova requested changes
also, you should remove all the branches except this one and `master`

2020-10-16 07:59 UTC, KseniiaMakarova commented on src/main/java/online/shop/controller/InjectDataController.java
> +        admin.setRoles(Set.of(Role.of("ADMIN")));
you are saving admin and only then setting his roles

2020-10-16 07:59 UTC, KseniiaMakarova commented on src/main/java/online/shop/controller/InjectDataController.java
> +        Product apple = new Product("apple",12.45);
```suggestion
        Product apple = new Product("apple", 12.45);
```
add whitespaces after comma everywhere needed

2020-10-16 07:59 UTC, KseniiaMakarova commented on src/main/webapp/WEB-INF/views/inject-data.jsp
> +</center>
```suggestion
</center>
</body>
```
what do you think?

2020-10-16 07:59 UTC, KseniiaMakarova commented on README.md
> +**matviihuk.office@gmail.com**
let's add a hyperlink to your GitHub profile here instead (see markdown cheatsheet)

2020-10-20 02:45 UTC, merged